
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'EQUALS IDENT LBRACE NUMBER RBRACE STRINGnpc : IDENT IDENT LBRACE atributos RBRACEatributos : atributo\n                 | atributos atributoatributo : IDENT EQUALS valorvalor : NUMBER\n             | STRING\n             | IDENT'
    
_lr_action_items = {'IDENT':([0,2,4,6,7,8,10,11,12,13,14,],[2,3,5,5,-2,11,-3,-7,-4,-5,-6,]),'$end':([1,9,],[0,-1,]),'LBRACE':([3,],[4,]),'EQUALS':([5,],[8,]),'RBRACE':([6,7,10,11,12,13,14,],[9,-2,-3,-7,-4,-5,-6,]),'NUMBER':([8,],[13,]),'STRING':([8,],[14,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'npc':([0,],[1,]),'atributos':([4,],[6,]),'atributo':([4,6,],[7,10,]),'valor':([8,],[12,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> npc","S'",1,None,None,None),
  ('npc -> IDENT IDENT LBRACE atributos RBRACE','npc',5,'p_npc','parser.py',5),
  ('atributos -> atributo','atributos',1,'p_atributos_lista','parser.py',13),
  ('atributos -> atributos atributo','atributos',2,'p_atributos_lista','parser.py',14),
  ('atributo -> IDENT EQUALS valor','atributo',3,'p_atributo','parser.py',22),
  ('valor -> NUMBER','valor',1,'p_valor','parser.py',26),
  ('valor -> STRING','valor',1,'p_valor','parser.py',27),
  ('valor -> IDENT','valor',1,'p_valor','parser.py',28),
]
