
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ATACAR COMMA EQUALS IDENT IMPRIMIR LBRACE LPAREN NPC NUMBER RBRACE RPAREN STRINGprograma : instrucoesinstrucoes : instrucao instrucoes\n                  | instrucaoinstrucao : definicao_npc\n                 | acao_atacar\n                 | acao_imprimirdefinicao_npc : NPC IDENT LBRACE lista_atributos RBRACElista_atributos : atributo lista_atributos\n                       | atributoatributo : IDENT EQUALS valorvalor : NUMBER\n             | STRINGacao_atacar : ATACAR LPAREN IDENT COMMA IDENT RPARENacao_imprimir : IMPRIMIR LPAREN IDENT RPAREN'
    
_lr_action_items = {'NPC':([0,3,4,5,6,21,23,29,],[7,7,-4,-5,-6,-14,-7,-13,]),'ATACAR':([0,3,4,5,6,21,23,29,],[8,8,-4,-5,-6,-14,-7,-13,]),'IMPRIMIR':([0,3,4,5,6,21,23,29,],[9,9,-4,-5,-6,-14,-7,-13,]),'$end':([1,2,3,4,5,6,10,21,23,29,],[0,-1,-3,-4,-5,-6,-2,-14,-7,-13,]),'IDENT':([7,12,13,14,19,20,26,27,28,],[11,15,16,17,17,25,-10,-11,-12,]),'LPAREN':([8,9,],[12,13,]),'LBRACE':([11,],[14,]),'COMMA':([15,],[20,]),'RPAREN':([16,25,],[21,29,]),'EQUALS':([17,],[22,]),'RBRACE':([18,19,24,26,27,28,],[23,-9,-8,-10,-11,-12,]),'NUMBER':([22,],[27,]),'STRING':([22,],[28,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'programa':([0,],[1,]),'instrucoes':([0,3,],[2,10,]),'instrucao':([0,3,],[3,3,]),'definicao_npc':([0,3,],[4,4,]),'acao_atacar':([0,3,],[5,5,]),'acao_imprimir':([0,3,],[6,6,]),'lista_atributos':([14,19,],[18,24,]),'atributo':([14,19,],[19,19,]),'valor':([22,],[26,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> programa","S'",1,None,None,None),
  ('programa -> instrucoes','programa',1,'p_programa','parser.py',14),
  ('instrucoes -> instrucao instrucoes','instrucoes',2,'p_instrucoes','parser.py',19),
  ('instrucoes -> instrucao','instrucoes',1,'p_instrucoes','parser.py',20),
  ('instrucao -> definicao_npc','instrucao',1,'p_instrucao','parser.py',25),
  ('instrucao -> acao_atacar','instrucao',1,'p_instrucao','parser.py',26),
  ('instrucao -> acao_imprimir','instrucao',1,'p_instrucao','parser.py',27),
  ('definicao_npc -> NPC IDENT LBRACE lista_atributos RBRACE','definicao_npc',5,'p_definicao_npc','parser.py',33),
  ('lista_atributos -> atributo lista_atributos','lista_atributos',2,'p_lista_atributos','parser.py',43),
  ('lista_atributos -> atributo','lista_atributos',1,'p_lista_atributos','parser.py',44),
  ('atributo -> IDENT EQUALS valor','atributo',3,'p_atributo','parser.py',52),
  ('valor -> NUMBER','valor',1,'p_valor','parser.py',57),
  ('valor -> STRING','valor',1,'p_valor','parser.py',58),
  ('acao_atacar -> ATACAR LPAREN IDENT COMMA IDENT RPAREN','acao_atacar',6,'p_acao_atacar','parser.py',64),
  ('acao_imprimir -> IMPRIMIR LPAREN IDENT RPAREN','acao_imprimir',4,'p_acao_imprimir','parser.py',98),
]
